In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import pathlib as path
import plotly.express as px

In [7]:

file_path = r"C:\Users\heryn\OneDrive\Documents\Semester 1 2026\FIT 5120\iteration 1 brainboost\project brain health\Measured-physical-activity-and-sleep-all\MPASDC01.xlsx"

df = pd.read_excel(file_path, sheet_name="Table 1.1_Proportions", header=None)

print(df.head(20))

                                                   0   \
0   This tab contains table 1.1, proportion of per...
1                     Australian Bureau of Statistics
2   Table 1.1 Physical activity, by age and sex(a)...
3   National Nutrition and Physical Activity Surve...
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                            Average daily inactivity
8                                   Less than 9 hours
9                             9 to less than 10 hours
10                           10 to less than 11 hours
11                           11 to less than 12 hours
12                           12 to less than 13 hours
13                           13 to less than 14 hours
14                           14 to less than 15 hours
15                                   15 hours or more
16                                      Total persons
17            Average daily inactivity (Mean – h:min)
18              Average daily light physical activity
19                                  Less than 2 hours

                           1         2         3         4         5   \
0                         NaN       NaN       NaN       NaN       NaN
1                         NaN       NaN       NaN       NaN       NaN
2                         NaN       NaN       NaN       NaN       NaN
3                         NaN       NaN       NaN       NaN       NaN
4           Age group (years)       NaN       NaN       NaN       NaN
5                       18–24     25–34     35–44     45–54     55–64
6   Proportion of persons (%)       NaN       NaN       NaN       NaN
7                         NaN       NaN       NaN       NaN       NaN
8                         7.2       7.5       8.1       6.7       5.9
9                          11      10.9       9.7       9.5       8.7
10                       17.1        15      15.3      19.6      12.7
11                       29.7      24.1      24.3      21.9      25.3
12                       11.1      21.8      16.7      16.5      22.2
13                       12.5      10.9      15.1      14.9      15.8
14                        7.1       6.4       6.4       7.5       5.3
15                        4.4       3.4       4.4       3.4       4.2
16                        100       100       100       100       100
17                   11:38:00  11:40:00  11:41:00  11:44:00  11:53:00
18                        NaN       NaN       NaN       NaN       NaN
19                       28.3      23.8      19.8      21.5      22.5

          6                  7         8                  9         10  \
0        NaN                NaN       NaN                NaN       NaN
1        NaN                NaN       NaN                NaN       NaN
2        NaN                NaN       NaN                NaN       NaN
3        NaN                NaN       NaN                NaN       NaN
4        NaN                NaN       NaN                NaN    Sex(a)
5      65–74  75 years and over     18–64  65 years and over     Males
6        NaN                NaN       NaN                NaN       NaN
7        NaN                NaN       NaN                NaN       NaN
8          3                1.5       7.1                2.3       5.7
9        7.6                3.4       9.9                5.9       7.3
10      14.1                6.5      15.8                 11      12.9
11      23.9               18.3      24.5               21.6      23.9
12      20.5               27.1      18.4               23.2      20.4
13      14.8               20.4        14               17.1      15.5
14       9.8               15.6       6.5               12.2       9.5
15       6.4                7.3       3.9                6.8       4.9
16       100                100       100                100       100
17  12:12:00           12:47:00  11:44:00           12:26:00  12:03:00
18       NaN                NaN       NaN                NaN       NaN
19      26.6                 39      22.5               31.7      26.3

          11                              12
0        NaN                             NaN
1        NaN                             NaN
2        NaN                             NaN
3        NaN                             NaN
4        NaN                             NaN
5    Females  Total \n18 years \nand over(c)
6        NaN                             NaN
7        NaN                             NaN
8        6.2                             5.9
9       10.4                             8.9
10      16.2                            14.6
11      23.8                            23.8
12      18.8                            19.6
13      14.1                            14.7
14       6.4                             7.9
15       4.3                             4.6
16       100                             100
17  11:46:00                        11:54:00
18       NaN                             NaN
19      23.4                            24.8

In [8]:


# use row 5 for age-group column names
columns = ["category"] + df.iloc[5, 1:].tolist()

# keep the table body only
table = df.iloc[7:55, 0:len(columns)].copy()
table.columns = columns

# clean column names
table.columns = [str(col).strip() for col in table.columns]

# clean category text
table["category"] = table["category"].astype(str).str.strip()

# keep only 18–24 column
table_18_24 = table[["category", "18–24"]].copy()
table_18_24 = table_18_24.rename(columns={"18–24": "value"})

# remove blank rows
table_18_24 = table_18_24.dropna(subset=["category"])

# remove footnotes and copyright rows
table_18_24 = table_18_24[
    ~table_18_24["category"].str.contains("Footnotes|Commonwealth of Australia", case=False, na=False)
]

# remove hash symbol from values like #1,8
table_18_24["value"] = (
    table_18_24["value"]
    .astype(str)
    .str.replace("#", "", regex=False)
    .str.replace(",", ".", regex=False)
)

# convert to numeric where possible
table_18_24["value"] = pd.to_numeric(table_18_24["value"], errors="coerce")

print(table_18_24.head(30))

                                             category  value
7                            Average daily inactivity    NaN
8                                   Less than 9 hours    7.2
9                             9 to less than 10 hours   11.0
10                           10 to less than 11 hours   17.1
11                           11 to less than 12 hours   29.7
12                           12 to less than 13 hours   11.1
13                           13 to less than 14 hours   12.5
14                           14 to less than 15 hours    7.1
15                                   15 hours or more    4.4
16                                      Total persons  100.0
17            Average daily inactivity (Mean – h:min)    NaN
18              Average daily light physical activity    NaN
19                                  Less than 2 hours   28.3
20                             2 to less than 3 hours   43.7
21                             3 to less than 4 hours   19.9
22                                    4 hours or more    8.1
23                                      Total persons  100.0
24  Average daily light physical activity (Mean – ...    NaN
25  Average daily moderate and vigorous physical a...    NaN
26                               Less than 30 minutes    1.8
27                     30 minutes to less than 1 hour    9.8
28                           1 to less than 1.5 hours   17.2
29                           1.5 to less than 2 hours   16.8
30                           2 to less than 2.5 hours   25.9
31                           2.5 to less than 3 hours   15.3
32                                    3 hours or more   13.2
33                                      Total persons  100.0
34  Average daily moderate and vigorous physical a...    NaN
35           Average daily moderate physical activity    NaN
36                               Less than 30 minutes    1.8

In [9]:
# -----------------------------
# Create metric groups
# -----------------------------
current_group = None
groups = []

for cat in table_18_24["category"]:
    if "Average daily inactivity" in cat and "Mean" not in cat:
        current_group = "inactivity"
        groups.append(None)
    elif "Average daily light physical activity" in cat and "Mean" not in cat:
        current_group = "light_activity"
        groups.append(None)
    elif "Average daily moderate and vigorous physical activity" in cat and "Mean" not in cat:
        current_group = "moderate_vigorous"
        groups.append(None)
    elif "Average daily moderate physical activity" in cat and "Mean" not in cat:
        current_group = "moderate"
        groups.append(None)
    elif "Average daily vigorous physical activity" in cat and "Mean" not in cat:
        current_group = "vigorous"
        groups.append(None)
    else:
        groups.append(current_group)

table_18_24["metric_group"] = groups

# -----------------------------
# Remove rows you do not need
# -----------------------------
cleaned = table_18_24[
    ~table_18_24["category"].str.contains(
        "Average daily|Total persons|Footnotes|Commonwealth of Australia",
        case=False,
        na=False
    )
].copy()

# Remove rows without metric group
cleaned = cleaned.dropna(subset=["metric_group"])

# Reorder columns
cleaned = cleaned[["metric_group", "category", "value"]]

print(cleaned)

         metric_group                                           category  \
8          inactivity                                  Less than 9 hours
9          inactivity                            9 to less than 10 hours
10         inactivity                           10 to less than 11 hours
11         inactivity                           11 to less than 12 hours
12         inactivity                           12 to less than 13 hours
13         inactivity                           13 to less than 14 hours
14         inactivity                           14 to less than 15 hours
15         inactivity                                   15 hours or more
19     light_activity                                  Less than 2 hours
20     light_activity                             2 to less than 3 hours
21     light_activity                             3 to less than 4 hours
22     light_activity                                    4 hours or more
26  moderate_vigorous                               Less than 30 minutes
27  moderate_vigorous                     30 minutes to less than 1 hour
28  moderate_vigorous                           1 to less than 1.5 hours
29  moderate_vigorous                           1.5 to less than 2 hours
30  moderate_vigorous                           2 to less than 2.5 hours
31  moderate_vigorous                           2.5 to less than 3 hours
32  moderate_vigorous                                    3 hours or more
36           moderate                               Less than 30 minutes
37           moderate                     30 minutes to less than 1 hour
38           moderate                           1 to less than 1.5 hours
39           moderate                           1.5 to less than 2 hours
40           moderate                           2 to less than 2.5 hours
41           moderate                           2.5 to less than 3 hours
42           moderate                                    3 hours or more
46           vigorous                                          0 minutes
47           vigorous                                        1–4 minutes
48           vigorous                                        5–9 minutes
49           vigorous                                 10 minutes or more
53           vigorous  # proportion has a high margin of error and sh...
54           vigorous  Proportions may not add up to 100% due to roun...

    value
8     7.2
9    11.0
10   17.1
11   29.7
12   11.1
13   12.5
14    7.1
15    4.4
19   28.3
20   43.7
21   19.9
22    8.1
26    1.8
27    9.8
28   17.2
29   16.8
30   25.9
31   15.3
32   13.2
36    1.8
37   10.8
38   17.0
39   20.9
40   28.4
41   10.2
42   11.0
46    7.4
47   59.6
48   18.3
49   14.7
53    NaN
54    NaN

In [10]:
cleaned.head(20)

         metric_group                        category  value
8          inactivity               Less than 9 hours    7.2
9          inactivity         9 to less than 10 hours   11.0
10         inactivity        10 to less than 11 hours   17.1
11         inactivity        11 to less than 12 hours   29.7
12         inactivity        12 to less than 13 hours   11.1
13         inactivity        13 to less than 14 hours   12.5
14         inactivity        14 to less than 15 hours    7.1
15         inactivity                15 hours or more    4.4
19     light_activity               Less than 2 hours   28.3
20     light_activity          2 to less than 3 hours   43.7
21     light_activity          3 to less than 4 hours   19.9
22     light_activity                 4 hours or more    8.1
26  moderate_vigorous            Less than 30 minutes    1.8
27  moderate_vigorous  30 minutes to less than 1 hour    9.8
28  moderate_vigorous        1 to less than 1.5 hours   17.2
29  moderate_vigorous        1.5 to less than 2 hours   16.8
30  moderate_vigorous        2 to less than 2.5 hours   25.9
31  moderate_vigorous        2.5 to less than 3 hours   15.3
32  moderate_vigorous                 3 hours or more   13.2
36           moderate            Less than 30 minutes    1.8

In [11]:
cleaned.describe()

           value
count  30.000000
mean   16.673333
std    12.205791
min     1.800000
25%     9.900000
50%    13.950000
75%    19.500000
max    59.600000

In [12]:
import plotly.express as px

# filter inactivity
inactivity = cleaned[cleaned["metric_group"] == "inactivity"].copy()

fig = px.bar(
    inactivity,
    x="value",
    y="category",
    orientation="h",
    text="value",
    title="Daily Inactivity Distribution for Ages 18–24",
    labels={"value": "Percentage", "category": "Inactivity duration"},
    hover_data={"value": ":.1f"}
)

fig.update_traces(
    texttemplate="%{text:.1f}%",
    textposition="outside"
)

fig.update_layout(
    yaxis=dict(categoryorder="array", categoryarray=inactivity["category"][::-1]),
    template="plotly_white",
    height=550,
    title_x=0.5
)

fig.show()

In [13]:

mvpa = cleaned[cleaned["metric_group"] == "moderate_vigorous"].copy()

fig = px.bar(
    mvpa,
    x="value",
    y="category",
    orientation="h",
    text="value",
    title="Moderate and Vigorous Physical Activity for Ages 18–24",
    labels={"value": "Percentage", "category": "Activity duration"},
    hover_data={"value": ":.1f"}
)

fig.update_traces(
    texttemplate="%{text:.1f}%",
    textposition="outside"
)

fig.update_layout(
    yaxis=dict(categoryorder="array", categoryarray=mvpa["category"][::-1]),
    template="plotly_white",
    height=550,
    title_x=0.5
)

fig.show()

In [14]:
import plotly.express as px

main_cleaned = cleaned[
    cleaned["metric_group"].isin(["inactivity", "moderate_vigorous"])
].copy()

main_cleaned["metric_group"] = main_cleaned["metric_group"].replace({
    "inactivity": "Daily Inactivity",
    "moderate_vigorous": "Moderate + Vigorous Activity"
})

fig = px.bar(
    main_cleaned,
    x="category",
    y="value",
    color="metric_group",
    barmode="group",
    text="value",
    title="Movement Profile for Ages 18–24",
    labels={
        "category": "Duration band",
        "value": "Percentage",
        "metric_group": "Metric"
    },
    hover_data={"value": ":.1f"}
)

fig.update_traces(
    texttemplate="%{text:.1f}%",
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    height=650,
    title_x=0.5,
    xaxis_tickangle=-30
)

fig.show()

In [15]:
import plotly.graph_objects as go

# filter inactivity only
inactivity = cleaned[cleaned["metric_group"] == "inactivity"].copy()

# average inactivity for 18–24
avg_inactivity = 11.38

fig = go.Figure()

# bar chart
fig.add_trace(go.Bar(
    x=inactivity["category"],
    y=inactivity["value"],
    text=inactivity["value"],
    textposition="outside",
    name="Percentage of 18–24",
    hovertemplate="Band: %{x}<br>Percentage: %{y:.1f}%<extra></extra>"
))

# vertical line for average
fig.add_vline(
    x=3,  # this will be placed around the 11 to <12 hours band
    line_width=3,
    line_dash="dash",
    annotation_text=f"Average inactivity = {avg_inactivity} hours",
    annotation_position="top"
)

fig.update_layout(
    title="Daily Inactivity Distribution for Ages 18–24",
    xaxis_title="Inactivity duration",
    yaxis_title="Percentage",
    template="plotly_white",
    height=600,
    title_x=0.5
)

fig.show()

In [18]:
import plotly.graph_objects as go
import pandas as pd

# Prepare data for line chart with averages
main_cleaned = cleaned[
    cleaned["metric_group"].isin(["inactivity", "moderate_vigorous"])
].copy()

main_cleaned["metric_group"] = main_cleaned["metric_group"].replace({
    "inactivity": "Daily Inactivity",
    "moderate_vigorous": "Moderate + Vigorous Activity"
})

# Calculate average for each metric group
averages = main_cleaned.groupby("metric_group")["value"].mean().reset_index()
averages.columns = ["metric_group", "average"]

print("Averages for each category:")
print(averages)

# Create line chart
fig = go.Figure()

for metric in main_cleaned["metric_group"].unique():
    metric_data = main_cleaned[main_cleaned["metric_group"] == metric]
    
    fig.add_trace(go.Scatter(
        x=metric_data["category"],
        y=metric_data["value"],
        mode="lines+markers",
        name=metric,
        line=dict(width=3),
        marker=dict(size=8),
        hovertemplate="Duration: %{x}<br>Percentage: %{y:.1f}%<extra></extra>"
    ))

# Add average lines
for _, row in averages.iterrows():
    fig.add_hline(
        y=row["average"],
        line_dash="dash",
        annotation_text=f"{row['metric_group']} Avg: {row['average']:.2f}%",
        annotation_position="right"
    )

fig.update_layout(
    title="Movement Profile for Ages 18–24",
    xaxis_title="Duration band",
    yaxis_title="Percentage",
    template="plotly_white",
    height=600,
    title_x=0.5,
    hovermode="x unified",
    xaxis_tickangle=-30
)

fig.show()

Averages for each category:
                   metric_group    average
0              Daily Inactivity  12.512500
1  Moderate + Vigorous Activity  14.285714